# -*- coding: utf-8 -*-
"""Uji Kuesioner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194-9o4QcYOGMkwLGfpOJyG9eRYAg0-DZ
"""

import pandas as pd
import numpy as np

df = pd.read_csv('data_kuesioner.csv', header=None)
print("Preview Data:")
print(df.head())
print("-" * 30)

def hitung_cronbach_alpha(df):
    """
    Fungsi untuk menghitung Cronbach's Alpha
    Berdasarkan rumus matematis: a = (k / (k-1)) * (1 - (sum(var_item) / var_total))
    """
    # Jumlah pertanyaan (k)
    k = df.shape[1]

    # Hitung varians dari setiap pertanyaan (varians per kolom)
    # ddof=1 digunakan untuk sampel (unbiased)
    varians_per_item = df.var(ddof=1)
    jumlah_varians_item = varians_per_item.sum()

    # Hitung skor total setiap responden (jumlahkan nilai per baris)
    skor_total_responden = df.sum(axis=1)

    # Hitung varians dari skor total
    varians_total = skor_total_responden.var(ddof=1)

    # Rumus Cronbach's Alpha
    alpha = (k / (k - 1)) * (1 - (jumlah_varians_item / varians_total))

    return alpha

# 2. Panggil fungsi dan tampilkan hasil
nilai_alpha = hitung_cronbach_alpha(df)

print(f"Jumlah Responden (n) : {df.shape[0]}")
print(f"Jumlah Pertanyaan (k): {df.shape[1]}")
print(f"Nilai Cronbach's Alpha : {nilai_alpha:.4f}")

# 3. Interpretasi Hasil
print("-" * 30)
if nilai_alpha >= 0.8:
    print("Interpretasi: Sangat Reliabel (Sangat Konsisten)")
elif nilai_alpha >= 0.6:
    print("Interpretasi: Reliabel (Dapat diterima / Konsisten)")
else:
    print("Interpretasi: Tidak Reliabel (Ada pertanyaan yang membingungkan responden)")